[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L

build_flags =
    -DMRJ_DISPLAY_ST7735
    -DMRJ_DISPLAY_TYPE=5
    -DMRJ_DISPLAY_WIDTH=128
    -DMRJ_DISPLAY_HEIGHT=160

lib_deps =
    olikraus/U8g2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit ILI9488
    bblanchon/ArduinoJson
    esp32async/AsyncTCP
    esp32async/ESPAsyncWebServer
    DNSServer