[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L

build_flags =
    -DMRJ_DISPLAY_ILI9488_35
    -DMRJ_DISPLAY_WIDTH=320
    -DMRJ_DISPLAY_HEIGHT=480

lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
    me-no-dev/AsyncTCP
    me-no-dev/ESP Async WebServer
    DNSServer
    adafruit/Adafruit ILI9488
    adafruit/Adafruit GFX Library
