[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L

build_flags =
    -DMRJ_DISPLAY_ST7789_154
    -DMRJ_DISPLAY_WIDTH=240
    -DMRJ_DISPLAY_HEIGHT=240

lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
    me-no-dev/AsyncTCP
    me-no-dev/ESP Async WebServer
    DNSServer
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
